.\" Copyright (C) 2013-24 Kevin Boone 
.\" Permission is granted to any individual or institution to use, copy, or
.\" redistribute this software so long as all of the original files are
.\" included, and that this copyright notice is retained.
.\"
.TH tonegen 1 "June 2024"
.SH NAME
tonegen \- Play various tones and sounds to ALSA 
.SH SYNOPSIS
.B tonegen 
.RB [options] 
.PP

.SH DESCRIPTION
\fItonegen\fR is simple utility for playing musical tones and noises
directly to an ALSA device. For more information, please see
https://github.com/kevinboone/tonegen 

.\" end of file
